### ISSUE TITLE
Expo link is dead 😭

### ISSUE THREAD

**Issue by zachgibson** [ggomaeng/react-native-spotify-ui#2]
Y expo link no work?

**Comment by ggomaeng** [comment]
I'm not sure :-( The expo links are going down for some reason--my tetris one also went down. Maybe they have an expiration date? I'll look into it, but for now you can just clone the repo and run it locally.

**Comment by cvng** [comment]
Link still down, no clue?

**Comment by louisiscoding** [comment]
Looks like you have to push a new version of it like once per month to keep it alive

**Comment by ggomaeng** [comment]
@LouisJS Darn, I did not know about that. Closing this since I currently don't have intentions to push new updates once per month.
